export enum ERoutePathName {
  Any = '*',
  Auth = 'auth',
  Create = 'create',
  Empty = 'empty',
  ForgotPassword = 'forgotPassword',
  Github = 'github',
  Home = 'home',
  Model = 'model',
  ModelId = ':modelId',
  Project = 'project',
  ProjectId = ':projectId',
  ProjectList = 'projects',
  Setting = 'setting',
  SignIn = 'signIn',
  SignUp = 'signUp',
  ViewId = ':viewId',
  Workspace = 'workspace',
  WorkspaceId = ':workspaceId',
}

export enum ERoutePath {
  AuthForgotPassword = '/auth/forgotPassword',
  AuthSignIn = '/auth/signIn',
  AuthSignUp = '/auth/signUp',
  Home = '/home',
  ProjectInstance = '/project/:projectId',
  ProjectDataModel = '/project/:projectId/model/:modelId',
  ProjectDataModelEmpty = '/project/:projectId/model/empty',
  ProjectDataView = '/project/:projectId/model/:modelId/view/:viewId',
  Root = '/',
  SignIn = '/signIn',
  Setting = '/setting',
  Workspace = '/workspace',
  WorkspaceCreate = '/workspace/create',
  WorkspaceInstance = '/workspace/:workspaceId',
  WorkspaceMemberList = '/workspace/:workspaceId/members',
  WorkspaceProjectList = '/workspace/:workspaceId/projects',
}
