export enum ERoutePathName {
  Any = '*',
  Auth = 'Auth',
  Create = 'create',
  ForgotPassword = 'forgotPassword',
  Home = '',
  Project = 'project',
  ProjectId = ':projectId',
  ModelId = ':modelId',
  Setting = 'setting',
  SignIn = 'signIn',
  SignUp = 'signUp',
  Workspace = 'workspace',
  WorkspaceId = ':workspaceId',
}

export enum ERoutePath {
  AuthForgotPassword = '/auth/forgotPassword',
  AuthSignIn = '/auth/signIn',
  AuthSignUp = '/auth/signUp',
  Home = '/',
  ProjectInstance = '/project/:projectId',
  ProjectDataModel = '/project/:projectId/:modelId',
  Root = '/',
  SignIn = '/signIn',
  Setting = '/setting',
  Workspace = '/workspace',
  WorkspaceCreate = '/workspace/create',
  WorkspaceInstance = '/workspace/:workspaceId',
}
