fragment IProject on Project {
  __typename
  objectId
  id
  title
  description
  visibility
  image
  color
}

mutation CreateProject($input: CreateProjectInput!) {
  createProject(input: $input) {
    project {
      ...IProject
    }
  }
}

query GetProject($id: ID!) {
  project(id: $id) {
    ...IProject
  }
}

query GetAllProjects {
  projects(order: updatedAt_DESC) {
    count
    edges {
      node {
        ...IProject
      }
    }
  }
}
