fragment IProject on Project {
  __typename
  objectId
  id
  title
  description
  visibility
  image
  color
}

fragment IProjectView on ProjectView {
  __typename
  objectId
  id
  title
  columnOrder {
    ... on Element {
      value
    }
  }
}

fragment IProjectColumn on ProjectColumn {
  __typename
  objectId
  id
  title
  itemOrder {
    ... on Element {
      value
    }
  }
}

mutation CreateProject($input: CreateProjectInput!) {
  createProject(input: $input) {
    project {
      ...IProject
    }
  }
}

query GetProject($id: ID!) {
  project(id: $id) {
    ...IProject
  }
  projectViews(where: { project: { have: { id: { equalTo: $id } } } }) {
    count
    edges {
      node {
        ...IProjectView
      }
    }
  }
  projectColumns(where: { project: { have: { id: { equalTo: $id } } } }) {
    count
    edges {
      node {
        ...IProjectColumn
      }
    }
  }
}

query GetAllProjects {
  projects(order: updatedAt_DESC) {
    count
    edges {
      node {
        ...IProject
      }
    }
  }
}
